import React, { useState } from 'react';
import Head from 'next/head';
import { useQuery } from 'react-query';

import http from '../services/http';
import DATA from '../constants/api';
import SearchBar from '../components/SearchBar';

const heading = 'text-2xl text-center';

export default function Home() {
  const [filteredCities, setFilteredCities] = useState([]);
  const [search, setSearch] = useState('');

  const { isLoading, data } = useQuery(
    ['getCities'],
    () => http.get({
      url: DATA.GET_DATA,
    }),
    { refetchOnWindowFocus: false },
  );

  const cities = data?.response?.results?.map(({ city }) => city);

  const filterAllCities = (searchTerm) => {
    const newCities = cities.slice();
    setSearch(searchTerm);

    if (!searchTerm) {
      setFilteredCities('');
    } else {
      setFilteredCities(newCities.filter(
        (city) => city.toLowerCase().includes(searchTerm.toLowerCase()),
      ));
    }
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="container mx-auto max-w-[700px]">
        {isLoading && <h1 className={heading}>Loading...</h1>}

        {data?.error && <h1 className={heading}>Something has gone wrong...</h1>}

        {data?.success && <h1 className={heading}>Compare your cities</h1>}

        <SearchBar handleClick={filterAllCities} className="mx-auto mt-4 md:w-3/4" />

        {search && filteredCities.length === 0
        && (
        <p
          className="mx-auto md:w-3/4 mt-4 text-center max-h-[200px]"
        >
          No results matching your search
        </p>
        )}

        {filteredCities.length > 0
        && (
        <ul className="mx-auto rounded-lg shadow-lg md:w-3/4 overflow-y-scroll max-h-[200px] snap-y">
          {filteredCities.slice(0, 10).map((city) => (
            <li
              key={city}
              className="px-4 py-2 cursor-pointer even:bg-neutral-200 odd:bg-slate-300 hover:bg-amber-400 snap-end"
            >
              {city}
            </li>
          ))}
        </ul>
        )}

      </main>
    </div>
  );
}
