import React from 'react';
import Head from 'next/head';
import { useQuery } from 'react-query';
import http from '../services/getData';
import DATA from '../constants/api';

export default function Home() {
  const { isLoading, isError, data } = useQuery(['getCities'], () => http.get({
    url: DATA.GET_DATA,
  }), { refetchOnWindowFocus: false });

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <h1 className="text-3xl font-bold underline">
          Welcome to
          {' '}
          <a href="https://nextjs.org">Next.js!</a>
        </h1>

      </main>

    </div>
  );
}
